# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgsort < Formula
  desc "Sort blocks and attributes in Terragrunt HCL files"
  homepage "https://github.com/salemgolemugoo/tgsort"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.2.1/tgsort_0.2.1_darwin_amd64.tar.gz"
      sha256 "70fdc11e6ce1ccbb2a660186b75df843b6ddb209f971e01e342369fd47ed6c36"

      define_method(:install) do
        bin.install "tgsort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.2.1/tgsort_0.2.1_darwin_arm64.tar.gz"
      sha256 "cc174b1a8f5b4f0587e6674b712c54a7772a6d7e7dc85535058998ea71bd956b"

      define_method(:install) do
        bin.install "tgsort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.2.1/tgsort_0.2.1_linux_amd64.tar.gz"
      sha256 "4f0111f11a31432ba1b54f2904a41222d337e0be55ea05fd0b86a9edcd9ac065"
      define_method(:install) do
        bin.install "tgsort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.2.1/tgsort_0.2.1_linux_arm64.tar.gz"
      sha256 "29c7c13194f72c705569d5a410c0458d8a31b55eb1c408edaceb4f2da9760df6"
      define_method(:install) do
        bin.install "tgsort"
      end
    end
  end

  test do
    system "#{bin}/tgsort", "--version"
  end
end
