# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgsort < Formula
  desc "Sort blocks and attributes in Terragrunt HCL files"
  homepage "https://github.com/salemgolemugoo/tgsort"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.3.0/tgsort_0.3.0_darwin_amd64.tar.gz"
      sha256 "d28d822930760daacdc0f4da2caa4c849bcb30c749cdf342180cec18ffc2ffb0"

      define_method(:install) do
        bin.install "tgsort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.3.0/tgsort_0.3.0_darwin_arm64.tar.gz"
      sha256 "062fb2ff0664e11b6b9b9c467d6cee4a713446f4e5bb1a814d9de7d8cc7b8c33"

      define_method(:install) do
        bin.install "tgsort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.3.0/tgsort_0.3.0_linux_amd64.tar.gz"
      sha256 "5dffa45e94aebd94b2724bb6a36116c38463e22eb708f07cb4ab5f4b928a3ef8"
      define_method(:install) do
        bin.install "tgsort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.3.0/tgsort_0.3.0_linux_arm64.tar.gz"
      sha256 "c25c790b245b3ba60e4cbc1f9f8aac267ed16c4efba3623a359b833c89d9624d"
      define_method(:install) do
        bin.install "tgsort"
      end
    end
  end

  test do
    system "#{bin}/tgsort", "--version"
  end
end
