# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgsort < Formula
  desc "Sort blocks and attributes in Terragrunt HCL files"
  homepage "https://github.com/salemgolemugoo/tgsort"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.1.0/tgsort_0.1.0_darwin_amd64.tar.gz"
      sha256 "26f094715b80085a04b272adeb17bb950e4badc25afd8ca5ce78ca0d4213d3ed"

      define_method(:install) do
        bin.install "tgsort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.1.0/tgsort_0.1.0_darwin_arm64.tar.gz"
      sha256 "5e2937713e90396bac039837ef3d9ce75b04d3027ee9be229ea3c82f42befa42"

      define_method(:install) do
        bin.install "tgsort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.1.0/tgsort_0.1.0_linux_amd64.tar.gz"
      sha256 "7daf1e0b6db0ab7f8a69139b2ff4b438f5804b1fa4bfec0c80f84f702b3f0394"
      define_method(:install) do
        bin.install "tgsort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salemgolemugoo/tgsort/releases/download/v0.1.0/tgsort_0.1.0_linux_arm64.tar.gz"
      sha256 "9931f2343e480e53d8c37671dff0ee40432128f96cec1f081f5c298f77a3d724"
      define_method(:install) do
        bin.install "tgsort"
      end
    end
  end

  test do
    system "#{bin}/tgsort", "--version"
  end
end
